name: CI/CD Pipeline

on:
  push:
    branches: jon-test
  pull_request:
    branches: jon-test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Create .env.test file
        run: |
          echo "DATABASE_URL=${{ secrets.TEST_DATABASE_URL }}" >> .env.test
          echo "DIRECT_URL=${{ secrets.TEST_DIRECT_URL }}" >> .env.test

      - name: Run tests
        run: npm test
        env:
          NODE_ENV: test # This tells your app to use .env.test


  # # deploy:
  #   needs: test  # Only run deploy if tests pass
  #   if: github.ref == 'refs/heads/main' # Only deploy on main branch
  #   runs-on: ubuntu-latest
  #   environment: production

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '18'

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Create .env file
  #       run: |
  #         echo "DATABASE_URL=${{ secrets.PROD_DATABASE_URL }}" >> .env
  #         echo "API_KEY=${{ secrets.PROD_API_KEY }}" >> .env

  #     - name: Deploy
  #       run: npm run deploy  # Or your deployment command
  #       env:
  #         NODE_ENV: production
